import { DataInputEnum } from '../../../base/types/edit-input.types';

// TINYBLOB：最大长度为 255 字节。
// BLOB：最大长度为 65,535 字节（即 64 KiB）。
// MEDIUMBLOB：最大长度为 16,777,215 字节（即 16 MiB）。
// LONGBLOB：最大长度为 4,294,967,295 字节（即 4 GiB）。
export enum MysqlColumnEnum {
  BIT = 'bit',
  BOOL = 'bool',
  TINYINT = 'tinyint',
  SMALLINT = 'smallint',
  MEDIUMINT = 'mediumint',
  INT = 'int',
  BIGINT = 'bigint',
  FLOAT = 'float',
  DOUBLE = 'double',
  DECIMAL = 'decimal',
  CHAR = 'char',
  VARCHAR = 'varchar',
  TINYTEXT = 'tinytext',
  TEXT = 'text',
  MEDIUMTEXT = 'mediumtext',
  LONGTEXT = 'longtext',
  DATE = 'date',
  TIME = 'time',
  DATETIME = 'datetime',
  TIMESTAMP = 'timestamp',
  YEAR = 'year',
  BINARY = 'binary',
  VARBINARY = 'varbinary',
  TINYBLOB = 'tinyblob',
  BLOB = 'blob',
  MEDIUMBLOB = 'mediumblob',
  LONGBLOB = 'longblob',
  ENUM = 'enum',
  SET = 'set',
  JSON = 'json',
  GEOMETRY = 'geometry',
  POINT = 'point',
  LINESTRING = 'linestring',
  POLYGON = 'polygon',
  MULTIPOINT = 'multipoint',
  MULTILINESTRING = 'multilinestring',
  MULTIPOLYGON = 'multipolygon',
  GEOMETRYCOLLECTION = 'geometrycollection',
}

export enum MysqlAutoIncrementType {
  AutoIncrement = 'auto_increment',
}

//
// export const MysqlColumnType: IColumnType[] = [
//   //常用放前面
//   {label: MysqlColumnEnum.INT, value: MysqlColumnEnum.INT},
//   {label: MysqlColumnEnum.BIGINT, value: MysqlColumnEnum.BIGINT},
//   {label: MysqlColumnEnum.VARCHAR, value: MysqlColumnEnum.VARCHAR},
//   {label: MysqlColumnEnum.DATETIME, value: MysqlColumnEnum.DATETIME},
//   {label: MysqlColumnEnum.TIMESTAMP, value: MysqlColumnEnum.TIMESTAMP},
//   {label: MysqlColumnEnum.DATE, value: MysqlColumnEnum.DATE},
//   {label: MysqlColumnEnum.FLOAT, value: MysqlColumnEnum.FLOAT},
//   {label: MysqlColumnEnum.DOUBLE, value: MysqlColumnEnum.DOUBLE},
//   {label: MysqlColumnEnum.CHAR, value: MysqlColumnEnum.CHAR},
//   //后面的是不常用的
//   {label: MysqlColumnEnum.BIT, value: MysqlColumnEnum.BIT},
//   {label: MysqlColumnEnum.BOOL, value: MysqlColumnEnum.BOOL},
//   {label: MysqlColumnEnum.TINYINT, value: MysqlColumnEnum.TINYINT},
//   {label: MysqlColumnEnum.SMALLINT, value: MysqlColumnEnum.SMALLINT},
//   {label: MysqlColumnEnum.MEDIUMINT, value: MysqlColumnEnum.MEDIUMINT},
//
//   {label: MysqlColumnEnum.TINYTEXT, value: MysqlColumnEnum.TINYTEXT},
//   {label: MysqlColumnEnum.TEXT, value: MysqlColumnEnum.TEXT},
//   {label: MysqlColumnEnum.MEDIUMTEXT, value: MysqlColumnEnum.MEDIUMTEXT},
//   {label: MysqlColumnEnum.LONGTEXT, value: MysqlColumnEnum.LONGTEXT},
//
//   {label: MysqlColumnEnum.TIME, value: MysqlColumnEnum.TIME},
//   {label: MysqlColumnEnum.YEAR, value: MysqlColumnEnum.YEAR},
//   {label: MysqlColumnEnum.BINARY, value: MysqlColumnEnum.BINARY},
//   {label: MysqlColumnEnum.VARBINARY, value: MysqlColumnEnum.VARBINARY},
//   {label: MysqlColumnEnum.TINYBLOB, value: MysqlColumnEnum.TINYBLOB},
//   {label: MysqlColumnEnum.BLOB, value: MysqlColumnEnum.BLOB},
//   {label: MysqlColumnEnum.MEDIUMBLOB, value: MysqlColumnEnum.MEDIUMBLOB},
//   {label: MysqlColumnEnum.LONGBLOB, value: MysqlColumnEnum.LONGBLOB},
//   {label: MysqlColumnEnum.ENUM, value: MysqlColumnEnum.ENUM},
//   {label: MysqlColumnEnum.SET, value: MysqlColumnEnum.SET},
//   {label: MysqlColumnEnum.GEOMETRY, value: MysqlColumnEnum.GEOMETRY},
//   {label: MysqlColumnEnum.POINT, value: MysqlColumnEnum.POINT},
//   {label: MysqlColumnEnum.LINESTRING, value: MysqlColumnEnum.LINESTRING},
//   {label: MysqlColumnEnum.POLYGON, value: MysqlColumnEnum.POLYGON},
//   {label: MysqlColumnEnum.MULTIPOINT, value: MysqlColumnEnum.MULTIPOINT},
//   {label: MysqlColumnEnum.MULTILINESTRING, value: MysqlColumnEnum.MULTILINESTRING},
//   {label: MysqlColumnEnum.MULTIPOLYGON, value: MysqlColumnEnum.MULTIPOLYGON},
//   {label: MysqlColumnEnum.GEOMETRYCOLLECTION, value: MysqlColumnEnum.GEOMETRYCOLLECTION}
// ]

/**
 * mysql 下拉类型选择
 */
export const MysqlColumnType: string[] = [
  //常用放前面
  MysqlColumnEnum.INT,
  MysqlColumnEnum.BIGINT,
  MysqlColumnEnum.VARCHAR,
  MysqlColumnEnum.DATETIME,
  MysqlColumnEnum.TIMESTAMP,
  MysqlColumnEnum.DATE,
  MysqlColumnEnum.FLOAT,
  MysqlColumnEnum.DOUBLE,
  MysqlColumnEnum.CHAR,
  MysqlColumnEnum.DECIMAL,
  //后面的是不常用的
  MysqlColumnEnum.BIT,
  MysqlColumnEnum.BOOL,
  MysqlColumnEnum.JSON,
  MysqlColumnEnum.TINYINT,
  MysqlColumnEnum.SMALLINT,
  MysqlColumnEnum.MEDIUMINT,
  MysqlColumnEnum.TINYTEXT,
  MysqlColumnEnum.TEXT,
  MysqlColumnEnum.MEDIUMTEXT,
  MysqlColumnEnum.LONGTEXT,
  MysqlColumnEnum.TIME,
  MysqlColumnEnum.YEAR,
  MysqlColumnEnum.BINARY,
  MysqlColumnEnum.VARBINARY,
  MysqlColumnEnum.TINYBLOB,
  MysqlColumnEnum.BLOB,
  MysqlColumnEnum.MEDIUMBLOB,
  MysqlColumnEnum.LONGBLOB,
  MysqlColumnEnum.ENUM,
  MysqlColumnEnum.SET,
  MysqlColumnEnum.GEOMETRY,
  MysqlColumnEnum.POINT,
  MysqlColumnEnum.LINESTRING,
  MysqlColumnEnum.POLYGON,
  MysqlColumnEnum.MULTIPOINT,
  MysqlColumnEnum.MULTILINESTRING,
  MysqlColumnEnum.MULTIPOLYGON,
  MysqlColumnEnum.GEOMETRYCOLLECTION,
];

//char varchar binary

export const enum MysqlIdType {
  BIT = 16,
  BOOL = 1,
  TINYINT = 1,
  SMALLINT = 2,
  MEDIUMINT = 9,
  INT = 3,
  BIGINT = 8,
  FLOAT = 4,
  DOUBLE = 5,
  DECIMAL = 246,
  CHAR = 254,
  VARCHAR = 253,
  TINYTEXT = 252,
  TEXT = 252,
  MEDIUMTEXT = 252,
  LONGTEXT = 252,
  DATE = 10,
  TIME = 11,
  DATETIME = 12,
  TIMESTAMP = 7,
  YEAR = 13,
  BINARY = 254,
  VARBINARY = 253,
  TINYBLOB = 252,
  BLOB = 252,
  MEDIUMBLOB = 252,
  LONGBLOB = 252,
  ENUM = 254,
  SET = 254,
  JSON = 245,
  GEOMETRY = 255,
  POINT = 255,
  LINESTRING = 255,
  POLYGON = 255,
  MULTIPOINT = 255,
  MULTILINESTRING = 255,
  MULTIPOLYGON = 255,
  GEOMETRYCOLLECTION = 255,
}
