import { DataInputEnum } from '../../../base/types/edit-input.types';

export enum PostgresColumnEnum {
  BOOL = 'bool',
  BYTEA = 'bytea',
  CHAR = 'char',
  INT8 = 'int8',
  INT2 = 'int2',
  INT4 = 'int4',
  REGPROC = 'regproc',
  TEXT = 'text',
  ARRAY = 'text[]',
  OID = 'oid',
  TID = 'tid',
  XID = 'xid',
  CID = 'cid',
  JSON = 'json',
  XML = 'xml',
  PG_NODE_TREE = 'pg_node_tree',
  SMGR = 'smgr',
  PATH = 'path',
  POLYGON = 'polygon',
  CIDR = 'cidr',
  FLOAT4 = 'float4',
  FLOAT8 = 'float8',
  ABSTIME = 'abstime',
  RELTIME = 'reltime',
  TINTERVAL = 'tinterval',
  CIRCLE = 'circle',
  MACADDR8 = 'macaddr8',
  MONEY = 'money',
  MACADDR = 'macaddr',
  INET = 'inet',
  ACLITEM = 'aclitem',
  BPCHAR = 'bpchar',
  VARCHAR = 'varchar',
  DATE = 'date',
  TIME = 'time',
  TIMESTAMP = 'timestamp',
  TIMESTAMPTZ = 'timestamptz',
  INTERVAL = 'interval',
  TIMETZ = 'timetz',
  BIT = 'bit',
  VARBIT = 'varbit',
  NUMERIC = 'numeric',
  REFCURSOR = 'pefcursor',
  REGPROCEDURE = 'regprocedure',
  REGOPER = 'pegoper',
  REGOPERATOR = 'regoperator',
  REGCLASS = 'regclass',
  REGTYPE = 'regtype',
  UUID = 'uuid',
  TXID_SNAPSHOT = 'txid_snapshot',
  PG_LSN = 'pg_lsn',
  PG_NDISTINCT = 'pg_ndistinct',
  PG_DEPENDENCIES = 'pg_dependencies',
  TSVECTOR = 'tsvector',
  TSQUERY = 'tsquery',
  GTSVECTOR = 'gtsvector',
  REGCONFIG = 'regconfig',
  REGDICTIONARY = 'regdictionary',
  JSONB = 'jsonb',
  REGNAMESPACE = 'regnamespace',
  REGROLE = 'regrole',
}

export enum PostgresAutoIncrementEnum {
  SMALLSERIAL = 'SMALLSERIAL',
  SERIAL = 'SERIAL',
  BIGSERIAL = 'BIGSERIAL',
}

export const PostgresColumnType: string[] = [
  PostgresColumnEnum.INT2,
  PostgresColumnEnum.INT4,
  PostgresColumnEnum.INT8,

  PostgresColumnEnum.CHAR,
  PostgresColumnEnum.VARCHAR,

  PostgresColumnEnum.DATE,
  PostgresColumnEnum.TIME,
  PostgresColumnEnum.TIMESTAMP,

  PostgresColumnEnum.FLOAT4,
  PostgresColumnEnum.FLOAT8,
  PostgresColumnEnum.NUMERIC,

  PostgresColumnEnum.UUID,

  PostgresColumnEnum.BOOL,
  PostgresColumnEnum.BYTEA,

  PostgresColumnEnum.REGPROC,
  PostgresColumnEnum.TEXT,
  PostgresColumnEnum.ARRAY,
  PostgresColumnEnum.OID,
  PostgresColumnEnum.TID,
  PostgresColumnEnum.XID,
  PostgresColumnEnum.CID,
  PostgresColumnEnum.JSON,
  PostgresColumnEnum.XML,
  PostgresColumnEnum.PG_NODE_TREE,
  PostgresColumnEnum.SMGR,
  PostgresColumnEnum.PATH,
  PostgresColumnEnum.POLYGON,
  PostgresColumnEnum.CIDR,
  PostgresColumnEnum.ABSTIME,
  PostgresColumnEnum.RELTIME,
  PostgresColumnEnum.TINTERVAL,
  PostgresColumnEnum.CIRCLE,
  PostgresColumnEnum.MACADDR8,
  PostgresColumnEnum.MONEY,
  PostgresColumnEnum.MACADDR,
  PostgresColumnEnum.INET,
  PostgresColumnEnum.ACLITEM,
  PostgresColumnEnum.BPCHAR,

  PostgresColumnEnum.TIMESTAMPTZ,
  PostgresColumnEnum.INTERVAL,
  PostgresColumnEnum.TIMETZ,
  PostgresColumnEnum.BIT,
  PostgresColumnEnum.VARBIT,

  PostgresColumnEnum.REFCURSOR,
  PostgresColumnEnum.REGPROCEDURE,
  PostgresColumnEnum.REGOPER,
  PostgresColumnEnum.REGOPERATOR,
  PostgresColumnEnum.REGCLASS,
  PostgresColumnEnum.REGTYPE,
  PostgresColumnEnum.TXID_SNAPSHOT,
  PostgresColumnEnum.PG_LSN,
  PostgresColumnEnum.PG_NDISTINCT,
  PostgresColumnEnum.PG_DEPENDENCIES,
  PostgresColumnEnum.TSVECTOR,
  PostgresColumnEnum.TSQUERY,
  PostgresColumnEnum.GTSVECTOR,
  PostgresColumnEnum.REGCONFIG,
  PostgresColumnEnum.REGDICTIONARY,
  PostgresColumnEnum.JSONB,
  PostgresColumnEnum.REGNAMESPACE,
  PostgresColumnEnum.REGROLE,
];

export enum PostgresTypeId {
  BOOL = 16,
  BYTEA = 17,
  CHAR = 18,
  INT8 = 20,
  INT2 = 21,
  INT4 = 23,
  REGPROC = 24,
  TEXT = 25,

  OID = 26,
  TID = 27,
  XID = 28,
  CID = 29,
  JSON = 114,
  XML = 142,
  PG_NODE_TREE = 194,
  SMGR = 210,
  PATH = 602,
  POLYGON = 604,
  CIDR = 650,
  FLOAT4 = 700,
  FLOAT8 = 701,
  ABSTIME = 702,
  RELTIME = 703,
  TINTERVAL = 704,
  CIRCLE = 718,
  MACADDR8 = 774,
  MONEY = 790,
  MACADDR = 829,
  INET = 869,
  ARRAY = 1009,
  ACLITEM = 1033,
  BPCHAR = 1042,
  VARCHAR = 1043,
  DATE = 1082,
  TIME = 1083,
  TIMESTAMP = 1114,
  TIMESTAMPTZ = 1184,
  INTERVAL = 1186,
  TIMETZ = 1266,
  BIT = 1560,
  VARBIT = 1562,
  NUMERIC = 1700,
  REFCURSOR = 1790,
  REGPROCEDURE = 2202,
  REGOPER = 2203,
  REGOPERATOR = 2204,
  REGCLASS = 2205,
  REGTYPE = 2206,
  UUID = 2950,
  TXID_SNAPSHOT = 2970,
  PG_LSN = 3220,
  PG_NDISTINCT = 3361,
  PG_DEPENDENCIES = 3402,
  TSVECTOR = 3614,
  TSQUERY = 3615,
  GTSVECTOR = 3642,
  REGCONFIG = 3734,
  REGDICTIONARY = 3769,
  JSONB = 3802,
  REGNAMESPACE = 4089,
  REGROLE = 4096,
}
